<?php
require '../../../connect.php';
require '../../../user.php';
$candidateid=$_SESSION['candidateid'];
$userrole=$_SESSION['userrole'];
?>	
<head>
    <link rel="stylesheet" href="Qvision\commonstyle.css">
</head>
<style>
.card-primary:not(.card-outline)>.card-header{
    background-color: #f1cc61 !important;
}
</style>
<div class="card card-primary">
    <div class="card-header">
        <h3 class="card-title" style="float: left;"><font size="5">QUOTE SEND LIST</font></h3>
        <!--  <a onclick="back_ctc()" style="float: right;" data-toggle="modal" class="btn btn-dark">BACK</a>-->
    </div>
           
    <div class="card-body">
    <table class="table table-striped table-bordered table-hover display nowrap" id="example1" style="width:100%">
      <thead>
      <th>#</th>
      <th>Cost Sheet No </th>
      <th>Quote No </th>
      <th>Product/Service </th>
      <th>Quote Type</th> 
      <th>Client Name</th>
      <th>Employee Name</th>
      <th>Status</th>
      <th>Action</th>
      </thead>
      <tbody>
	
      <?php
      $roll_query = $con->prepare("SELECT code from z_role_master WHERE id = '$userrole' ");
      $roll_query->execute(); 
      $row = $roll_query->fetch(PDO::FETCH_ASSOC);

      if($row && ($row['code'] == 'R006' || $row['code'] == 'R005' || $row['code'] == 'R004')) {
          // FIX: Added 'IS NOT NULL' to handle null values securely
          $datas=$con->query("SELECT a.id as costsheet_id,a.status as cs_status,a.cost_sheet_no as cs_no,a.candid_id as quote_approve_id,a.*,b.*,e.*,f.*,h.quote_no as hquote_no,h.* from cost_sheet_entry a 
                  left join new_client_master b on(a.client_id=b.id) 
                  left join product_services f on (a.business_id=f.id)
                  left join staff_master e ON (a.candid_id=e.candid_id)  
                  left join quote_generate h on(a.cost_sheet_no=h.cost_sheet_no)
                  where a.status ='2' and a.created_by='$candidateid' and h.quote_no IS NOT NULL and h.quote_no!='' group by a.cost_sheet_no  order by a.id desc");
      }else{
          // FIX: Added 'IS NOT NULL' here as well
          $datas=$con->query("SELECT a.id as costsheet_id,a.status as cs_status,a.cost_sheet_no as cs_no,a.candid_id as quote_approve_id,a.*,b.*,e.*,f.*,h.quote_no as hquote_no,h.* from cost_sheet_entry a 
                  left join new_client_master b on(a.client_id=b.id) 
                  left join product_services f on (a.business_id=f.id)
                  left join staff_master e ON (a.candid_id=e.candid_id)  
                  left join quote_generate h on(a.cost_sheet_no=h.cost_sheet_no)
                  where a.status ='2' and h.quote_no IS NOT NULL and h.quote_no!='' group by a.cost_sheet_no  order by a.id desc");
      }
		
      $cnt=1;
      while($data =$datas->fetch(PDO::FETCH_ASSOC))
      {
          $approved_id = $data['quote_approve_id'];

          $stmt = $con->prepare("SELECT emp_name from staff_master where candid_id ='$approved_id' "); 	
          $stmt->execute(); 
          $row = $stmt->fetch(PDO::FETCH_ASSOC);
          if($row){
              $emp_name = $row['emp_name'];
          } else {
              $emp_name = '-'; 
          }
      ?>
      <tr>
          <td><?php echo $cnt;?>.</td>
          <td><?php echo $data['cs_no']; ?></td>
          <td><?php echo $data['hquote_no']; ?></td>
          <td><?php 
          // FIX: Changed mapping_id to business_id 
          if($data['business_id'] =='1'){ echo "Product"; 
          }elseif($data['business_id'] =='2'){ echo "Service";
          }elseif($data['business_id'] =='3'){ echo "Solution";
          }
          ?></td>
          <td><?php if($data['quote_type']=='1'){ echo "INR"; }else{ echo "Doller";}?></td>
         
          <td><?php echo $data['org_name']; ?></td>
          <td><?php echo $emp_name; ?></td>
          <td><?php  if($data['cs_status']==2){ 
           echo '<span style="color:green;text-align:center;"><b>Quote Generated By - ' ;?>
                   <?php echo $emp_name; } ?> 
          </td>
          <td>  
             <!-- FIX: Changed enquiry_id to costsheet_id inside onclick -->
             <button class="btn btn-info" data-id="<?php echo $data['costsheet_id']; ?>" onclick="quote_proposal_view(<?php echo $data['costsheet_id']; ?>)">
             <i class="fa fa-eye"></i></button>
          </td>
      </tr>
      <?php
      $cnt=$cnt+1;
      }
      ?>
      </tbody>
      </table>
      </div>
</div>
<script>
$(document).ready(function() {
    $('#example1').DataTable( {
        "scrollY": 400,
        "scrollX": true
    } );
} );
</script>
<script>
 $(function () {
    $("#dataTable").DataTable({
      "responsive": true,
      "autoWidth": false,
    });
     $('#dataTable').DataTable({
      "paging": true,
      "lengthChange": false,
      "searching": false,
       "ordering": true,
       "info": true,
      "autoWidth": false,
      "responsive": true,
     });
   });

function quote_proposal_view(v){
    //alert(v);
    $.ajax({
    type:"POST",
    url:"qvision/BusinessProcess/quotation/quotation_send_view.php?id="+v+"&page_id="+ '1', //"page_id =1 " To find page for Quotation send  back button action. 
    success:function(data)
    {
        $("#main_content").html(data);
    }
    })
}
function back_ctc()
{
    Quotation_view();
}
</script>